import requests
import base64
import os

def update_github_docs(repo: str, file_path: str, scan_summary: str):
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        print("[bold red]Error: GITHUB_TOKEN environment variable is missing.[/bold red]")
        print("Please run: export GITHUB_TOKEN='your_personal_access_token'")
        return False

    url = f"https://api.github.com/repos/{repo}/contents/{file_path}"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }

    response = requests.get(url, headers=headers)
    sha = None
    if response.status_code == 200:
        sha = response.json().get('sha')
    elif response.status_code != 404:
        print(f"Error fetching repo data: {response.json()}")
        return False

    markdown_content = f"# DocScanSec Security Report\n\n{scan_summary}\n\n*Auto-generated by DocScanSec.*"
    encoded_content = base64.b64encode(markdown_content.encode('utf-8')).decode('utf-8')

    data = {
        "message": "docs(security): auto-update vulnerability report [skip ci]",
        "content": encoded_content,
    }
    if sha:
        data["sha"] = sha

    put_response = requests.put(url, headers=headers, json=data)
    
    if put_response.status_code in [200, 201]:
        print(f"[bold green] Successfully updated {file_path} in {repo}![/bold green]")
        return True
    else:
        print(f"[bold red] Failed to push update to GitHub: {put_response.json()}[/bold red]")
        return False